#!/bin/sh
### BEGIN INIT INFO
# Provides:          dsremap
# Required-Start:    networking bluetooth
# Required-Stop:     networking bluetooth
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: DSRemap HTTP server
# Description:       DSRemap HTTP server
### END INIT INFO

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
	if [ ! -e /var/run/dsremap.pid ]; then
	    /opt/dsremap/dsremap_serve -d
	    for idx in 0 1 2 3 4 5 6 7 8 9; do
		if [ -e /var/run/dsremap.pid ]; then
		    break
		fi
	    done
	fi
	;;
    stop)
	if [ -e /var/run/dsremap.pid ]; then
	    kill `cat /var/run/dsremap.pid`
	    for idx in 0 1 2 3 4 5 6 7 8 9; do
		if [ ! -e /var/run/dsremap.pid ]; then
		    break
		fi
	    done
	fi
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	;;
esac
